### PR TITLE
Testing feedback

### PR DESCRIPTION
**Pull request by bwalsh**
This PR:
* improves documentation
* sets up k8s proxy on master
* improves user experience by eliminating  'update  known_hosts' messages

### CODE REVIEW

**Comment by kellrott** [comment]
I'm still getting forced interactive conformation the first time the script tries to SSH to the newly created nodes.

```
Attempted contact to k8test-funnel-worker2. FAILED, sleeping 10 secs
The authenticity of host '10.50.50.158 (10.50.50.158)' can't be established.
ECDSA key fingerprint is SHA256:yzFpR1nsb0TBKCdcs2hTQoKZoLQ96h8OJHY4MtiltnA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.50.50.158' (ECDSA) to the list of known hosts.
```

**Comment by kellrott** [comment]
On first login and attempt at `kubectl`, still getting:
```
error: error loading config file "/home/ubuntu/.kube/config": open /home/ubuntu/.kube/config: permission denied
```

**Comment by kellrott** [comment]
After fixing permissions issues, it seems like the proxy isn't listening. I still get:
```
ubuntu@k8test-funnel-master:~$ kubectl get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Strangely, the proxy is listed under `ps`:

```
ubuntu@k8test-funnel-master:~$ ps auxww | grep proxy
root     16962  0.7  2.2 210048 91368 ?        Ssl  19:46   0:08 kube-controller-manager --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --use-service-account-credentials=true
root     17036  2.2  8.2 493496 331300 ?       Ssl  19:46   0:27 kube-apiserver --advertise-address=10.50.50.156 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
root     17611  0.0  0.7 139624 30604 ?        Ssl  19:46   0:00 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=k8test-funnel-master
```

**Comment by bwalsh** [comment]
@kellrott 

> I'm still getting forced interactive conformation the first time the script tries to SSH to the newly created nodes.

Update your .env   ?

From updated README.md

image

**Comment by kellrott** [comment]
Ok, update to the .env worked

**Comment by bwalsh** [comment]
@kellrott 
Added changes to ensure proxy runs in background and kubctrl works.
The ./k8_status.sh now calls get pods and does not use sudo.

```
./k8_status.sh
NODES:
NAME                 STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION      CONTAINER-RUNTIME
bw-k8-test-master    Ready    master   11m     v1.16.3   10.50.50.167   <none>        Ubuntu 18.04 LTS   4.15.0-72-generic   docker://18.6.2
bw-k8-test-worker1   Ready    <none>   9m39s   v1.16.3   10.50.50.168   <none>        Ubuntu 18.04 LTS   4.15.0-72-generic   docker://18.6.2
bw-k8-test-worker2   Ready    <none>   9m15s   v1.16.3   10.50.50.169   <none>        Ubuntu 18.04 LTS   4.15.0-72-generic   docker://18.6.2
PODS:
No resources found in default namespace.
```

**Comment by kellrott** [comment]
:+1:

**Pull request merged**
